package com.crossover.techtrial.service;

import com.crossover.techtrial.dto.DailyElectricity;
import com.crossover.techtrial.model.HourlyElectricity;
import com.crossover.techtrial.repository.HourlyElectricityRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.NoSuchElementException;

/**
 * HourlyElectricityServiceImpl will handle electricity generated by a Panel.
 *
 * @author Ahmed Yehia
 */

@Service
public class HourlyElectricityServiceImpl implements HourlyElectricityService {
    @Autowired
    HourlyElectricityRepository hourlyElectricityRepository;

    public HourlyElectricity save(HourlyElectricity hourlyElectricity) {
        return hourlyElectricityRepository.save(hourlyElectricity);
    }

    public Page<HourlyElectricity> getAllHourlyElectricityByPanelId(Long panelId, Pageable pageable) {
        return hourlyElectricityRepository.findAllByPanelIdOrderByReadingAtDesc(panelId, pageable);
    }

    public List<DailyElectricity> getDailyStatistics(String panelSerial) {
        List<DailyElectricity> result = hourlyElectricityRepository.getDailyStatistics(panelSerial);
        return result;
    }


}